//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbalifeScoreApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APACScoreEntities : DbContext
    {
        public APACScoreEntities()
            : base("name=APACScoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HL_CodeTable> HL_CodeTable { get; set; }
        public virtual DbSet<HL_Web_Agreement> HL_Web_Agreement { get; set; }
        public virtual DbSet<HL_Web_AgreementDetail> HL_Web_AgreementDetail { get; set; }
        public virtual DbSet<HL_Web_Master_ItemDetail> HL_Web_Master_ItemDetail { get; set; }
        public virtual DbSet<HL_Web_Master_ItemHeader> HL_Web_Master_ItemHeader { get; set; }
        public virtual DbSet<HL_Web_ReportData_KPITP_Data> HL_Web_ReportData_KPITP_Data { get; set; }
        public virtual DbSet<HL_Web_ReportData_KPIWH_Data> HL_Web_ReportData_KPIWH_Data { get; set; }
        public virtual DbSet<HL_Web_Task> HL_Web_Task { get; set; }
        public virtual DbSet<HL_Web_Vendor> HL_Web_Vendor { get; set; }
        public virtual DbSet<HL_Web_VendorUserMapping> HL_Web_VendorUserMapping { get; set; }
        public virtual DbSet<HL_Web_Warehouse> HL_Web_Warehouse { get; set; }
        public virtual DbSet<HL_Web_Win_ReportData_KPITP_Data> HL_Web_Win_ReportData_KPITP_Data { get; set; }
        public virtual DbSet<HL_Web_Win_ReportData_KPIWH_Data> HL_Web_Win_ReportData_KPIWH_Data { get; set; }
        public virtual DbSet<HL_Web_Win_ReportData_SCTP_Data> HL_Web_Win_ReportData_SCTP_Data { get; set; }
        public virtual DbSet<HL_Web_Win_ReportData_SCWH_Data> HL_Web_Win_ReportData_SCWH_Data { get; set; }
        public virtual DbSet<HL_Web_Win_Task> HL_Web_Win_Task { get; set; }
        public virtual DbSet<HL_Country> HL_Country { get; set; }
        public virtual DbSet<HL_Web_VendorUser> HL_Web_VendorUser { get; set; }
    }
}
