//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbalifeScoreApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL_CodeTable
    {
        public string Category { get; set; }
        public string Code { get; set; }
        public string CodeName { get; set; }
        public Nullable<int> SortSeq { get; set; }
    }
}
