//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HerbalifeScoreApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HL_Web_Agreement
    {
        public int AgreementId { get; set; }
        public string CountryCode { get; set; }
        public string AgreementType { get; set; }
        public string TransportType { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string WHCode { get; set; }
        public Nullable<System.DateTime> PeriodFrom { get; set; }
        public Nullable<System.DateTime> PeriodTo { get; set; }
        public string ServiceProvide { get; set; }
        public string OtherComment { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ChangeUser { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    }
}
